#!/usr/bin/env python3
"""
Planner node for KleaAgent

File: klea_agent/nodes/planner.py

Copyright 2026 Ankur Sinha
Author: Ankur Sinha <sanjay DOT ankur AT gmail dot com>
"""

import logging
from typing import Any, ClassVar, Literal, override

from klea_utils.llm import extract_llm_output_content, prompt_value_to_messages
from klea_utils.mcp.access import DEFAULT_ACCESS_LEVEL, filter_tools_info
from klea_utils.mcp.schemas import ToolInfo
from klea_utils.nodes.abstract import NodeStreamData
from klea_utils.nodes.base import BaseLLMNode
from langchain_core.messages import AIMessage

from klea_agent.schemas import KleaAgentState, PlannerOutput, PlanSchema


class Planner(BaseLLMNode[KleaAgentState, PlannerOutput]):
    """Task-path brain for the general path (ADR-0035).

    It writes the immutable goal and creates or revises the evolvable plan.
    ``plan.status`` carries the routing outcome (``in_review`` | ``in_progress``
    | ``unplannable``); there is no separate route flag.  Chat is handled by
    ``RouteDecision`` and the final reply by ``AnswerFromResults``, so the
    Planner never answers the user.

    Uses the tool descriptions generated by ``BaseLangGraph._build_tools_info``
    (``self._tools_info``) -- the orchestrator passes ``tools_info`` via
    ``set_tools_info`` before the graph is compiled.  This keeps the
    available-tools list consistent with ``ToolsPicker`` and the MCP registry.
    """

    model_type = "plan"
    model_defaults: ClassVar[dict[str, Any]] = {
        "temperature": 0.01,
        "max_output_tokens": 4096,
    }
    #: Re-invoke the model with the validation error when it returns a
    #: structurally inconsistent plan (dangling dependencies, out-of-range
    #: current index, duplicate numbers).  Bounded so the node always returns.
    max_validation_retries: ClassVar[int] = 2

    def __init__(
        self,
        logger: logging.Logger,
        label: str,
        llm_models: dict[str, Any],
        memory: bool = False,
        max_plan_revisions: int = 4,
    ):
        """Initialise the planner node.

        :param logger: Logger instance
        :param label: Human-readable label for UI progress display
        :param llm_models: ``{role: LLMModel}`` dict (from ``BaseLangGraph.llm_models``)
        :param memory: Whether to include recent conversation history.  The
            Planner needs prior context (follow-ups and earlier failed plans),
            so the orchestrator passes ``memory=self.memory``.
        :param max_plan_revisions: Automated replans allowed in one run
            (since the initial plan or the last human review) before the
            Planner gives up (deterministic budget).  Human review re-entries
            reset the counter.
        """
        super().__init__(
            logger=logger,
            label=label,
            llm_models=llm_models,
            output_schema=PlannerOutput,
            memory=memory,
        )
        self.max_plan_revisions = max_plan_revisions
        self._tools_info: dict[str, dict[str, ToolInfo]] = {}

    def _get_tool_descriptions(self, state: KleaAgentState) -> str:
        """Return combined compact tool descriptions from ``_tools_info``.

        Uses ``ToolInfo.short_description`` (name plus docstring, no parameter
        list) so the planner prompt stays small under tiered disclosure
        (ADR-0035); the tool picker carries the full argument detail.  Falls
        back to ``description`` when a short form was not built.  Tools the
        state's ``access_level`` does not permit are excluded (ADR-0037), so
        the planner never plans around a disallowed tool.

        :param state: Current graph state (supplies the access level).
        :returns: Compact descriptions joined into one block.
        """
        access_level = getattr(state, "access_level", DEFAULT_ACCESS_LEVEL)
        tools_info = filter_tools_info(self._tools_info, access_level)
        self.logger.debug(
            f"{access_level = }\n"
            f"disclosed_tools = "
            f"{[name for domain in tools_info.values() for name in domain]}"
        )
        parts = [
            info.short_description or info.description or ""
            for domain_tools in tools_info.values()
            for info in domain_tools.values()
        ]
        return "\n\n".join(parts)

    def set_tools_info(self, tools_info: dict[str, dict[str, ToolInfo]]) -> None:
        """Set tool metadata (called by orchestrator after construction).

        Stores the per-domain ``ToolInfo`` map from ``BaseLangGraph.tools_info``;
        filtering by the run's access level happens per invocation in
        :meth:`_get_tool_descriptions`.
        """
        self._tools_info = tools_info or {}

    @override
    def _get_prompt_variables(self, state: KleaAgentState) -> dict:
        """Format prompt with the query, current plan state and tool catalogue."""
        goal_text = state.goal.goal or "(not set)"
        if state.goal.success_criteria:
            goal_text += f"\nSuccess criteria: {state.goal.success_criteria}"
        return {
            "query": state.query,
            "goal": goal_text,
            "plan": state.plan.render(),
            "human_feedback": state.human_feedback or "(none)",
            "replan_reason": state.replan_reason or "(none)",
            "artefacts": state.artefacts_text(),
            "discovery": state.discovery_persistent,
            "observations": state.observations_text(),
            "tools_description": self._get_tool_descriptions(state),
            "validation_feedback": self._validation_feedback or "(none)",
        }

    @override
    def _validate_result(
        self, result: PlannerOutput, state: KleaAgentState
    ) -> str | None:
        """Reject a structurally inconsistent or contradictory plan.

        The Planner is the sole plan author; code does not repair its output.
        An inconsistent plan is retried with the errors exposed to the prompt
        as ``validation_feedback``.  Checks:

        * ``status == "unplannable"`` must not carry steps;
        * structural plan consistency (:meth:`PlanSchema.validate_plan`);
        * ``kind``/tool consistency: a ``tool`` step names at least one tool,
          a ``reasoning`` step names none.

        An empty plan with a non-``unplannable`` status is not an error --
        :meth:`_update_state` deterministically coerces it to ``unplannable``.
        """
        if not isinstance(result, PlannerOutput):
            return None
        errors: list[str] = []
        plan = result.plan
        if plan.status == "unplannable" and plan.step_list:
            errors.append(
                "status is 'unplannable' but steps were returned; "
                "return no steps or set a runnable status"
            )
        if plan.step_list:
            errors.extend(plan.validate_plan())
            for step in plan.step_list:
                if step.kind == "tool" and not step.suggested_tools:
                    errors.append(
                        f"step {step.step_number} is a tool step but names no tool"
                    )
                if step.kind == "reasoning" and step.suggested_tools:
                    errors.append(
                        f"step {step.step_number} is a reasoning step but names tools"
                    )
        return "; ".join(errors) if errors else None

    @override
    def _update_state(
        self, result: PlannerOutput, state: KleaAgentState
    ) -> dict[str, Any]:
        """Write the goal (locked) and the plan, trusting the model's plan.

        Design (ADR-0035): the Planner is the **sole author** of the plan,
        including each step's ``status`` and the ``current_step_index``.  Code
        does not re-apply completion markers or recompute the pointer by
        matching step numbers across plans (that positional matching was
        brittle and corrupt on renumbering).  The model is given the prior
        plan with its ``[DONE]`` markers and is responsible for carrying
        completed steps forward; ``PlannerOutput`` is validated structurally
        in :meth:`_validate_result` and retried if inconsistent.

        Goal handling (ADR-0035): the Planner is the sole goal writer, but it
        only sets the goal while it is unset, so a replan or review revision
        cannot move the success reference.  A freshly built ``PlanSchema`` is
        written rather than mutating the previous one.  The Planner never
        answers the user -- chat is handled by ``RouteDecision`` and the final
        reply by ``AnswerFromResults``.

        A ``needs_input`` status maps to the state plan with ``result.reason``
        carried as ``pending_question`` (a partial plan is allowed); an
        ``unplannable`` status (or an empty plan) fails the run, using
        ``result.reason`` as the failure explanation; a plan with steps maps
        the remaining statuses to the state plan.  ``result.reason`` is also
        recorded with the plan in ``messages`` for continuity.
        """
        update: dict[str, Any] = {"human_feedback": "", "replan_reason": ""}

        # --- Replan budget (deterministic) -------------------------------
        # Link the counter to the unified replan reason: an entry carrying a
        # ``replan_reason`` is an automated replan (Triage escalation,
        # Evaluator ``need_replan``, or picker failure) and consumes the
        # budget; the first plan and a human review re-entry carry no reason,
        # so they reset it.  Deriving from the reason keeps the two in
        # lockstep - a reason can never be present with a zero counter.
        # The ``in_progress`` status is a belt-and-braces fallback so a path
        # that forgets to set the reason still cannot bypass the budget
        # (logged below).
        is_replan = bool(state.replan_reason) or state.plan.status == "in_progress"
        if state.plan.status == "in_progress" and not state.replan_reason:
            self.logger.warning(
                "Planner re-entered with an in_progress plan but no "
                "replan_reason; counting it as a replan"
            )
        revisions = state.plan_revisions + 1 if is_replan else 0
        update["plan_revisions"] = revisions
        if revisions > self.max_plan_revisions:
            self.logger.warning(
                "Plan revision budget (%d) exhausted; giving up",
                self.max_plan_revisions,
            )
            update["plan"] = PlanSchema(status="unplannable")
            update["failure_reason"] = "plan revision budget exhausted"
            update["messages"] = [
                *state.messages,
                AIMessage(content="Planning failed: plan revision budget exhausted"),
            ]
            return update

        # --- Unplannable: the Planner's explicit signal, or no steps at all
        # (except ``needs_input``, which may carry a partial plan).
        # 'unplannable' with steps is rejected in _validate_result; a
        # non-unplannable status with no steps is a deterministic coercion.
        # Handled before the goal lock so a failed plan does not lock a goal.
        steps = result.plan.step_list
        if result.plan.status == "unplannable" or (
            not steps and result.plan.status != "needs_input"
        ):
            update["plan"] = PlanSchema(status="unplannable")
            update["failure_reason"] = (
                result.reason
                or "planner could not produc a plan with the available information"
            )
            update["messages"] = [
                *state.messages,
                AIMessage(content=f"Planning failed: {update['failure_reason']}"),
            ]
            self.logger.debug(f"{update = }")
            return update

        # Goal lock: write only while unset.
        if not state.goal.goal and result.goal.goal:
            update["goal"] = result.goal
        elif (
            state.goal.goal and result.goal.goal and result.goal.goal != state.goal.goal
        ):
            self.logger.warning(
                "Planner proposed a different goal; keeping the fixed goal (ADR-0035)"
            )

        if result.plan.status == "needs_input":
            # A partial plan is allowed: some steps may be runnable, but the
            # Planner needs a missing fact before it can finalise.  The
            # question travels in ``pending_question``; short-term the run ends
            # with the question (AnswerFromResults), and the HITL interrupt
            # will later resume this run with the answer.
            plan = PlanSchema(
                step_list=steps,
                status="needs_input",
                current_step_index=result.plan.current_step_index,
            )
            update["plan"] = plan
            update["pending_question"] = (
                result.reason or "More information is needed to continue."
            )
            update["step_outputs"] = {}
            update["tool_retry_counts"] = {}
            update["step_attempt_counts"] = {}
            message = f"Plan (needs_input):\n{plan.render()}"
            if result.reason:
                message += f"\nQuestion: {result.reason}"
            update["messages"] = [*state.messages, AIMessage(content=message)]
            self.logger.debug(f"{update = }")
            return update

        # The Planner decides whether the plan needs human review before it
        # runs (``in_review``) or is ready (``in_progress``).  ``human_feedback``
        # has been consumed by this LLM call and is cleared above.  The model's
        # per-step statuses and ``current_step_index`` are used unchanged.
        status: Literal["in_review", "in_progress"] = (
            "in_review" if result.plan.status == "in_review" else "in_progress"
        )
        plan = PlanSchema(
            step_list=steps,
            status=status,
            current_step_index=result.plan.current_step_index,
        )
        update["plan"] = plan
        # A replan replaces the step list: clear per-step execution state so
        # stale step keys cannot merge into (or trip the retry budgets of) the
        # new plan's steps.  The LLM call above already saw the prior
        # observations and feedback when it produced this plan.
        update["step_outputs"] = {}
        update["tool_retry_counts"] = {}
        update["step_attempt_counts"] = {}
        message = f"Plan ({status}):\n{plan.render()}"
        if result.reason:
            message += f"\nReason: {result.reason}"
        update["messages"] = [*state.messages, AIMessage(content=message)]
        self.logger.debug(f"{update = }")
        return update

    @override
    def _get_inspect(self) -> NodeStreamData:
        """Return the plan summary plus prompt and raw/processed output."""
        assert self._last_state is not None
        assert self._last_prompt is not None
        assert self._last_output is not None
        assert self._last_result is not None
        result = self._last_result
        if isinstance(result, PlannerOutput):
            summary = (
                f"Plan with {len(result.plan.step_list)} step(s), "
                f"status={result.plan.status}"
            )
        else:
            summary = "Planner output"
        return NodeStreamData(
            heading="Plan",
            summary=summary,
            details={
                "input_prompt": prompt_value_to_messages(self._last_prompt),
                "unprocessed_output": extract_llm_output_content(self._last_output),
                "processed_output": str(self._last_result),
                "tools_description": self._get_tool_descriptions(self._last_state),
            },
        )

    @override
    def _get_status(self) -> NodeStreamData | None:
        """Expose the current plan to the status pane (markdown).

        Reads the plan from ``_last_state_updates`` -- the plan this pass just
        produced -- falling back to the pre-execution ``_last_state.plan``.
        ``_last_state`` is captured at execution entry, so on a turn's first
        Planner pass it still holds the empty plan that
        :class:`InitGraphState` reset, which would render ``(no plan)``.
        """
        plan = None
        if self._last_state_updates:
            plan = self._last_state_updates.get("plan")
        if plan is None:
            state = self._last_state
            if state is None:
                return None
            plan = state.plan
        return NodeStreamData(
            heading="Plan",
            summary=f"{len(plan.step_list)} step(s); status={plan.status}",
            display=plan.render(markdown=True),
            key="plan",
            preformatted=True,
        )

    @override
    def _get_default_error_result(self) -> PlannerOutput:
        """Return an empty output; ``_update_state`` marks it ``unplannable``."""
        return PlannerOutput()
