#!/usr/bin/env python3
"""
Planner node for KleaAgent

See ``devdocs/system/agent-general-path-control-flow.md``; ADR-0041.

File: klea_agent/nodes/planner.py

Copyright 2026 Ankur Sinha
Author: Ankur Sinha <sanjay DOT ankur AT gmail dot com>
"""

import logging
from typing import Any, ClassVar, Literal, override

from klea_utils.llm import extract_llm_output_content, prompt_value_to_messages
from klea_utils.mcp.access import DEFAULT_ACCESS_LEVEL, filter_tools_info
from klea_utils.mcp.schemas import ToolInfo
from klea_utils.nodes.abstract import NodeStreamData
from klea_utils.nodes.base import BaseLLMNode
from klea_utils.nodes.context import LLMNodeContext
from langchain_core.messages import AIMessage

from klea_agent.schemas import KleaAgentState, PlannerOutput, PlanSchema


class Planner(BaseLLMNode[KleaAgentState, PlannerOutput]):
    """Task-path brain for the general path (ADR-0035).

    It writes the immutable goal and creates or revises the evolvable plan.
    ``plan.status`` carries the routing outcome (``in_review`` | ``in_progress``
    | ``unplannable``); there is no separate route flag.  Chat is handled by
    ``RouteDecision`` and the final reply by ``AnswerFromResults``, so the
    Planner never answers the user.

    Uses the tool descriptions generated by ``BaseLangGraph._build_tools_info``
    (passed as ``tools_info`` to the constructor).  This keeps the
    available-tools list consistent with ``ToolsPicker`` and the MCP registry.
    """

    model_role = "plan"
    model_defaults: ClassVar[dict[str, Any]] = {
        "temperature": 0.01,
    }
    #: Re-invoke the model with the validation error when it returns a
    #: structurally inconsistent plan (dangling dependencies, out-of-range
    #: current index, duplicate numbers).  Bounded so the node always returns.
    max_validation_retries: ClassVar[int] = 2

    def __init__(
        self,
        logger: logging.Logger,
        label: str,
        llm_models: dict[str, Any],
        memory: bool = False,
        max_automated_plan_revisions: int = 4,
        max_plan_steps: int = 30,
        tools_info: dict[str, dict[str, ToolInfo]] | None = None,
    ):
        """Initialise the planner node.

        :param logger: Logger instance
        :param label: Human-readable label for UI progress display
        :param llm_models: ``{role: LLMModel}`` dict (from ``BaseLangGraph.llm_models``)
        :param memory: Whether to include recent conversation history.  The
            Planner needs prior context (follow-ups and earlier failed plans),
            so the orchestrator passes ``memory=self.memory``.
        :param max_automated_plan_revisions: Automated replans allowed in one
            run (since the initial plan or the last human review) before the
            Planner gives up (deterministic budget).  Human review re-entries
            reset the counter.
        :param max_plan_steps: Runaway guard on the plan length.  A plan with
            more steps is rejected and retried; if the model still exceeds it,
            the run fails closed as ``unplannable`` (deliberately large, so it
            only catches a runaway plan, not a complex task).
        :param tools_info: Per-domain ``ToolInfo`` map from
            ``BaseLangGraph.tools_info`` (built before ``_create_graph``);
            filtered by the run's access level per invocation.
        """
        super().__init__(
            logger=logger,
            label=label,
            llm_models=llm_models,
            output_schema=PlannerOutput,
            memory=memory,
        )
        self.max_automated_plan_revisions = max_automated_plan_revisions
        self.max_plan_steps = max_plan_steps
        self._tools_info: dict[str, dict[str, ToolInfo]] = tools_info or {}

    def _get_tool_descriptions(self, state: KleaAgentState) -> str:
        """Return combined compact tool descriptions from ``_tools_info``.

        Uses ``ToolInfo.short_description`` (name plus docstring, no parameter
        list) so the planner prompt stays small under tiered disclosure
        (ADR-0035); the tool picker carries the full argument detail.  Falls
        back to ``description`` when a short form was not built.  Tools the
        state's ``access_level`` does not permit are excluded (ADR-0037), so
        the planner never plans around a disallowed tool.

        :param state: Current graph state (supplies the access level).
        :returns: Compact descriptions joined into one block.
        """
        access_level = getattr(state, "access_level", DEFAULT_ACCESS_LEVEL)
        tools_info = filter_tools_info(self._tools_info, access_level)
        self.logger.debug(
            f"{access_level = }\n"
            f"disclosed_tools = "
            f"{[name for domain in tools_info.values() for name in domain]}"
        )
        parts = [
            info.short_description or info.description or ""
            for domain_tools in tools_info.values()
            for info in domain_tools.values()
        ]
        return "\n\n".join(parts)

    @staticmethod
    def _render_human_input(state: KleaAgentState) -> str:
        """Render the user's needs_input answers against the steps that asked."""
        asked = {step.step_number: step.needs_input for step in state.plan.step_list}
        lines: list[str] = []
        for step_number, answers in state.human_input.items():
            questions = asked.get(step_number, [])
            for index, answer in enumerate(answers):
                question = questions[index] if index < len(questions) else "(question)"
                lines.append(f"- Step {step_number} Q: {question} A: {answer}")
        return "\n".join(lines)

    @override
    def _get_prompt_variables(self, state: KleaAgentState, ctx: Any) -> dict:
        """Format prompt with the query, current plan state and tool catalogue.

        The conditional feedback fields are composed into one optional
        ``feedback_block`` so the prompt omits them entirely when there is
        nothing to say (prompt conventions).
        """
        goal_text = state.goal.goal or "(not set)"
        if state.goal.success_criteria:
            goal_text += f"\nSuccess criteria: {state.goal.success_criteria}"
        feedback_block = "\n\n".join(
            section
            for section in (
                self._optional_section("Review feedback", state.human_feedback),
                self._optional_section("User input", self._render_human_input(state)),
                self._optional_section("Replan reason", state.replan_reason),
                self._optional_section("Validation feedback", ctx.validation_feedback),
            )
            if section
        )
        return {
            "query": state.query,
            "goal": goal_text,
            "plan": state.plan.render(),
            "feedback_block": feedback_block,
            "artefacts": state.artefacts_text(),
            "discovery": state.discovery_persistent.render(),
            "observations": state.observations_text(),
            "tools_description": self._get_tool_descriptions(state),
        }

    @override
    def _validate_result(
        self, result: PlannerOutput, state: KleaAgentState, ctx: Any
    ) -> str | None:
        """Reject a structurally inconsistent or contradictory plan.

        The Planner is the sole plan author; code does not repair its output.
        An inconsistent plan is retried with the errors exposed to the prompt
        as ``validation_feedback``.  Checks:

        * ``status == "unplannable"`` must not carry steps;
        * the plan does not exceed :attr:`max_plan_steps`;
        * structural plan consistency (:meth:`PlanSchema.validate_plan`);
        * ``kind``/tool consistency: a ``tool`` step names at least one tool,
          a ``reasoning`` step names none -- unless the step is **blocked** (it
          has ``needs_input`` questions), since a blocked step is a draft that
          is not executed and need not yet be runnable;
        * ``needs_input`` status must be accompanied by at least one blocked
          step (a question to ask).

        An empty plan with a non-``unplannable`` status is not an error --
        :meth:`_update_state` deterministically coerces it to ``unplannable``.
        """
        if not isinstance(result, PlannerOutput):
            return None
        errors: list[str] = []
        plan = result.plan
        if plan.status == "unplannable" and plan.step_list:
            errors.append(
                "status is 'unplannable' but steps were returned; "
                "return no steps or set a runnable status"
            )
        if len(plan.step_list) > self.max_plan_steps:
            errors.append(
                f"plan has {len(plan.step_list)} steps; at most "
                f"{self.max_plan_steps} are allowed - reduce the plan"
            )
        if plan.step_list:
            errors.extend(plan.validate_plan())
            for step in plan.step_list:
                if step.needs_input:
                    # A blocked step is a draft; it need not be runnable yet.
                    continue
                if step.kind == "tool" and not step.suggested_tools:
                    errors.append(
                        f"step {step.step_number} is a tool step but names no tool"
                    )
                if step.kind == "reasoning" and step.suggested_tools:
                    errors.append(
                        f"step {step.step_number} is a reasoning step but names tools"
                    )
        if plan.status == "needs_input" and not any(
            step.needs_input for step in plan.step_list
        ):
            errors.append(
                "status is 'needs_input' but no step has questions; "
                "attach the questions to the blocked step(s)"
            )
        return "; ".join(errors) if errors else None

    @override
    def _update_state(
        self, result: PlannerOutput, state: KleaAgentState, ctx: Any
    ) -> dict[str, Any]:
        """Write the goal (locked) and the plan, trusting the model's plan.

        Design (ADR-0035/ADR-0041): the Planner is the **sole author** of the
        plan, including each step's ``status`` and ``depends_on``.  Code does
        not re-apply completion markers or recompute positions by matching step
        numbers across plans (that positional matching was brittle and corrupt
        on renumbering).  The model is given the prior plan with its ``[DONE]``
        markers and is responsible for carrying completed steps forward;
        ``PlannerOutput`` is validated structurally in :meth:`_validate_result`
        and retried if inconsistent.

        Goal handling (ADR-0035): the Planner is the sole goal writer, but it
        only sets the goal while it is unset, so a replan or review revision
        cannot move the success reference.  A freshly built ``PlanSchema`` is
        written rather than mutating the previous one.  The Planner never
        answers the user -- chat is handled by ``RouteDecision`` and the final
        reply by ``AnswerFromResults``.

        A plan with any blocked step (a step carrying ``needs_input``
        questions) is written as a draft with status ``needs_input`` regardless
        of the model's status; an ``unplannable`` status (or an empty plan)
        fails the run, using ``result.reason`` as the failure explanation; a
        plan with steps maps the remaining statuses to the state plan.
        ``result.reason`` is also recorded with the plan in ``messages`` for
        continuity.
        """
        # The transient human/feedback inputs are consumed on this pass: the
        # prompt just read them, so clear them from state.  The blocked state
        # below is re-derived from the plan the Planner writes.
        update: dict[str, Any] = {
            "human_feedback": "",
            "human_input": {},
            "replan_reason": "",
        }

        # --- Plan-history counters (durable run signal) -------------------
        # ``plan_version`` increments on every authoring; ``human_feedback_rounds``
        # increments when the Planner processes review feedback; the automated
        # revision counter is the budget and resets on a human review.  These
        # live on the plan (``PlanSchema``) so the answer synthesis can be told
        # the final plan is a settled artifact without the raw feedback.
        prior = state.plan
        version = prior.plan_version + 1
        review_rounds = prior.human_feedback_rounds + (1 if state.human_feedback else 0)

        # --- Replan budget (deterministic) -------------------------------
        # Link the counter to the unified replan reason: an entry carrying a
        # ``replan_reason`` is an automated replan (Triage escalation,
        # Evaluator ``need_replan``, or picker failure) and consumes the
        # budget; the first plan and a human review re-entry carry no reason,
        # so they reset it.  Deriving from the reason keeps the two in
        # lockstep - a reason can never be present with a zero counter.
        # The ``in_progress`` status is a belt-and-braces fallback so a path
        # that forgets to set the reason still cannot bypass the budget
        # (logged below).
        is_replan = bool(state.replan_reason) or state.plan.status == "in_progress"
        if state.plan.status == "in_progress" and not state.replan_reason:
            self.logger.warning(
                "Planner re-entered with an in_progress plan but no "
                "replan_reason; counting it as a replan"
            )
        revisions = prior.automated_plan_revisions + 1 if is_replan else 0
        if revisions > self.max_automated_plan_revisions:
            self.logger.warning(
                "Plan revision budget (%d) exhausted; giving up",
                self.max_automated_plan_revisions,
            )
            update["plan"] = PlanSchema(
                status="unplannable",
                plan_version=version,
                human_feedback_rounds=review_rounds,
                automated_plan_revisions=revisions,
            )
            update["failure_reason"] = "plan revision budget exhausted"
            update["messages"] = [
                *state.messages,
                AIMessage(content="Planning failed: plan revision budget exhausted"),
            ]
            return update

        # --- Unplannable: the Planner's explicit signal, or no steps at all
        # (except ``needs_input``, which may carry a partial plan).
        # 'unplannable' with steps is rejected in _validate_result; a
        # non-unplannable status with no steps is a deterministic coercion.
        # Handled before the goal lock so a failed plan does not lock a goal.
        steps = result.plan.step_list
        if len(steps) > self.max_plan_steps:
            # Fail closed: the model did not comply after the validation
            # retries, so the runaway plan must not execute.
            self.logger.warning(
                "Plan has %d steps, over the %d-step limit; failing closed",
                len(steps),
                self.max_plan_steps,
            )
            update["plan"] = PlanSchema(
                status="unplannable",
                plan_version=version,
                human_feedback_rounds=review_rounds,
                automated_plan_revisions=revisions,
            )
            update["failure_reason"] = (
                f"plan exceeds the maximum of {self.max_plan_steps} steps"
            )
            update["messages"] = [
                *state.messages,
                AIMessage(content=f"Planning failed: {update['failure_reason']}"),
            ]
            self.logger.debug(f"{update = }")
            return update

        if result.plan.status == "unplannable" or (
            not steps and result.plan.status != "needs_input"
        ):
            update["plan"] = PlanSchema(
                status="unplannable",
                plan_version=version,
                human_feedback_rounds=review_rounds,
                automated_plan_revisions=revisions,
            )
            update["failure_reason"] = (
                result.reason
                or "planner could not produc a plan with the available information"
            )
            update["messages"] = [
                *state.messages,
                AIMessage(content=f"Planning failed: {update['failure_reason']}"),
            ]
            self.logger.debug(f"{update = }")
            return update

        # Goal lock: write only while unset.
        if not state.goal.goal and result.goal.goal:
            update["goal"] = result.goal
        elif (
            state.goal.goal and result.goal.goal and result.goal.goal != state.goal.goal
        ):
            self.logger.warning(
                "Planner proposed a different goal; keeping the fixed goal (ADR-0035)"
            )

        # A step with questions is blocked: the plan is a draft and cannot run
        # until the Planner re-authors it without questions (ADR-0046).  The
        # blocked state is derived deterministically from the steps, not taken
        # from the model's status (which may be out of sync).
        blocked = [step for step in steps if step.needs_input]
        if blocked:
            plan = PlanSchema(
                step_list=steps,
                status="needs_input",
                plan_version=version,
                human_feedback_rounds=review_rounds,
                automated_plan_revisions=revisions,
            )
            update["plan"] = plan
            update["step_outputs"] = {}
            update["tool_retry_counts"] = {}
            update["step_attempt_counts"] = {}
            lines = "\n".join(
                f"- Step {step.step_number}: {question}"
                for step in blocked
                for question in step.needs_input
            )
            message = f"Plan (needs_input):\n{plan.render()}\nQuestions:\n{lines}"
            update["messages"] = [*state.messages, AIMessage(content=message)]
            self.logger.debug(f"{update = }")
            return update

        # The Planner decides whether the plan needs human review before it
        # runs (``in_review``) or is ready (``in_progress``).  ``human_feedback``
        # has been consumed by this LLM call and is cleared above.  The model's
        # per-step statuses and ``depends_on`` are used unchanged (ADR-0041).
        status: Literal["in_review", "in_progress"] = (
            "in_review" if result.plan.status == "in_review" else "in_progress"
        )
        plan = PlanSchema(
            step_list=steps,
            status=status,
            plan_version=version,
            human_feedback_rounds=review_rounds,
            automated_plan_revisions=revisions,
        )
        # If the Planner carried every step forward as ``done`` there is
        # nothing left to run: mark the plan complete deterministically, so the
        # graph routes to the answer instead of the step entry (ADR-0041).
        if status == "in_progress" and all(
            step.status == "done" for step in plan.step_list
        ):
            plan.status = "completed"
        update["plan"] = plan
        # A replan replaces the step list: clear per-step execution state so
        # stale step keys cannot merge into (or trip the retry budgets of) the
        # new plan's steps.  The LLM call above already saw the prior
        # observations and feedback when it produced this plan.
        update["step_outputs"] = {}
        update["tool_retry_counts"] = {}
        update["step_attempt_counts"] = {}
        message = f"Plan ({status}):\n{plan.render()}"
        if result.reason:
            message += f"\nReason: {result.reason}"
        update["messages"] = [*state.messages, AIMessage(content=message)]
        self.logger.debug(f"{update = }")
        return update

    @override
    def _get_inspect(
        self, state: KleaAgentState, ctx: LLMNodeContext[Any]
    ) -> NodeStreamData:
        """Return the plan summary plus prompt and raw/processed output."""
        assert ctx.prompt is not None
        assert ctx.output is not None
        assert ctx.result is not None
        result = ctx.result
        if isinstance(result, PlannerOutput):
            summary = (
                f"Plan with {len(result.plan.step_list)} step(s), "
                f"status={result.plan.status}"
            )
        else:
            summary = "Planner output"
        return NodeStreamData(
            heading="Plan",
            summary=summary,
            details={
                "input_prompt": prompt_value_to_messages(ctx.prompt),
                "unprocessed_output": extract_llm_output_content(ctx.output),
                "processed_output": str(ctx.result),
                "tools_description": self._get_tool_descriptions(state),
            },
        )

    @override
    def _get_status(
        self, state: KleaAgentState, ctx: LLMNodeContext[Any]
    ) -> NodeStreamData | None:
        """Expose the current plan to the status pane (markdown).

        Reads the plan from ``ctx.state_updates`` -- the plan this pass just
        produced -- falling back to the pre-execution ``state.plan``.  The
        incoming state is captured at execution entry, so on a turn's first
        Planner pass it still holds the empty plan that
        :class:`InitGraphState` reset, which would render ``(no plan)``.
        """
        plan = None
        if ctx.state_updates:
            plan = ctx.state_updates.get("plan")
        if plan is None:
            plan = state.plan
        return NodeStreamData(
            heading="Plan",
            summary=f"{len(plan.step_list)} step(s); status={plan.status}",
            display=plan.render(markdown=True),
            key="plan",
            preformatted=True,
        )

    @override
    def _get_default_error_result(self, ctx: Any) -> PlannerOutput:
        """Return an empty output; ``_update_state`` marks it ``unplannable``."""
        return PlannerOutput()
